# Numpy
### 'pip install numpy'
### Numpy is incredibly fast and has bindings to c libraries numpy uses arrays rather than lists

## Numpy Arrays
### Numpy arrays essentially come with vectors and matrices, vectors are 1d arrays and matrices are 2d arrays.

In [2]:
import numpy as np

In [4]:
my_list = [3, 6, 9]
np.array(my_list)

array([3, 6, 9])

In [6]:
matrix1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.arange(0, 9, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.linspace(0, 9, 3)

array([0. , 4.5, 9. ])

In [29]:
np.linspace(0, 9, 50)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.rand(2)

array([0.43753479, 0.54704561])

In [35]:
np.random.rand(5,5)

array([[0.17942073, 0.90180074, 0.7981327 , 0.0997677 , 0.21132961],
       [0.15262529, 0.77909558, 0.45675995, 0.82123532, 0.59288735],
       [0.84092233, 0.11885851, 0.14988828, 0.31160945, 0.24626455],
       [0.2919927 , 0.58641244, 0.78121518, 0.99381286, 0.15220163],
       [0.85352013, 0.06189725, 0.3873779 , 0.34522033, 0.83267865]])

In [37]:
np.random.randn(2)

array([2.46514783, 0.19460361])

In [39]:
np.random.randn(5,5)

array([[-7.96247122e-01,  2.30311891e+00, -1.67204929e+00,
        -3.50894338e-02,  9.66170332e-01],
       [-6.64112861e-01, -1.19985715e+00,  1.96346896e+00,
        -6.16345286e-01, -2.63578861e-04],
       [ 7.31516968e-01,  2.01662701e+00,  2.46484419e-01,
         3.28724291e-01, -3.02581876e-01],
       [ 4.27776704e-01, -5.51319703e-01, -5.26013816e-01,
         1.62221950e+00, -7.56291492e-01],
       [ 1.47918308e+00, -3.08766130e-01, -1.13379198e+00,
        -7.03495681e-01,  9.79561362e-01]])

In [41]:
np.random.randint(0, 10)

9

In [43]:
np.random.randint(1, 50, 10)

array([10,  2, 31, 42,  5, 35,  3, 29, 10, 46])

In [46]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr

array([34, 27, 31, 36, 34, 42, 21, 23, 15, 26])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr

array([34, 27, 31, 36, 34, 42, 21, 23, 15, 26])

In [56]:
ranarr.max()

42

In [58]:
ranarr.argmax()

5

In [59]:
ranarr.min()

15

In [60]:
ranarr.argmin()

8

In [61]:
arr.shape

(25,)

In [64]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
arr.reshape(1, 25).shape

(1, 25)

In [67]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [69]:
arr.reshape(25, 1).shape

(25, 1)

In [70]:
arr.dtype

dtype('int32')